name: gentoo-openrc-musl-cloud
run-name: gentoo-openrc-musl-cloud
on:
  schedule:
    # work through your fika you poor bastard
    - cron: "12 00 * * mon"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  gentoo-openrc-musl-cloud:
    strategy:
      matrix:
        arch: [amd64, arm64]
    name: Make gentoo-openrc-musl-cloud-${{ matrix.arch }}
    runs-on: ubuntu-${{ matrix.arch }}-latest
    steps:
      - name: Acquire some space for kernel build
        run: |
          sudo rm -rf \
            /usr/share/dotnet
            /usr/local/lib/android
            /opt/ghc
            /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo df -h
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cd cloud-openrc-musl
          docker build \
            --platform linux/${{ matrix.arch }} -t gentoo-openrc-musl-cloud:latest .
          ./mkimg.sh gentoo-openrc-musl-cloud gentoo-openrc-musl-cloud-${{ matrix.arch }}.raw
          sha256sum -b gentoo-openrc-musl-cloud-${{ matrix.arch }}.raw |
            tee gentoo-openrc-musl-cloud-${{ matrix.arch }}.SHA256
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: gentoo-openrc-musl-cloud-${{ matrix.arch }}
          path: |
            gentoo-openrc-musl-cloud-${{ matrix.arch }}.raw
            gentoo-openrc-musl-cloud-${{ matrix.arch }}.SHA256
          retention-days: 14
